### ISSUE TITLE
Request to support Java 17

### ISSUE THREAD

**Issue by Preiter20** [spyhunter99/installcert#92]
Getting an error on RHEL 8.6 and Java 17:  

... loading system truststore from '/etc/pki/ca-trust/extracted/java/cacerts' ...
Opening connection to servername:8443...
... opening connection to servername:8443 ...
... starting SSL handshake ...
Exception in thread "main" java.lang.IllegalAccessError: class usn.net.ssl.util.InstallCert (in unnamed module @0xc2f0589) cannot access class sun.security.validator.ValidatorException (in module java.base) because module java.base does not export sun.security.validator to unnamed module @0xc2f0589
        at usn.net.ssl.util.InstallCert.getCerts(InstallCert.java:613)
        at usn.net.ssl.util.InstallCert.main(InstallCert.java:376)

**Comment by spyhunter99** [comment]
is this still an issue? i thought all references to ValidatorException were removed
